### ISSUE TITLE
Generated file header info issue

### ISSUE THREAD

**Issue by a-voronov** [SwiftKit/MockeryGenerator#4]
Hi! I'm currently testing Cuckoo to see if it can fit my project.
And the first issue I see is huge pull requests when working in a team.

This might happen because of writing file header for each generated token.
https://github.com/SwiftKit/CuckooGenerator/blob/b25906805cd55f857eeb78a0b9776c36e96765c1/Source/CuckooGeneratorFramework/FileHeaderHandlers/FileHeaderHandler_r1.swift#L14

So each team member will create their own version of this file which might also cause conflicts.
Otherwise this file should be ignored by git and generated by CI job runner.

But either way might be or not preferred by different groups of people.

What are your suggestions regarding this?

**Comment by TadeasKriz** [comment]
Hi, this generated file should be in your .gitignore and get generated before each tests. It will be changing as you will change protocols you want to mock, thus creating unnecessary commit changes.

Also, a new option will be added in the following days called `--no-header` which will disable the header generation.

**Comment by TadeasKriz** [comment]
Let me know if there is something we might do to make it more suitable for your project.

**Comment by a-voronov** [comment]
@TadeasKriz thanks! That would be really handy :)
I'll create few more issues I've faced with while generating mocks for classes and will see what can be improved.

**Comment by TadeasKriz** [comment]
Thanks! Hopefully we can improve it. There are some limitations of Swift unfortunately.

**Comment by TadeasKriz** [comment]
Fixed in Cuckoo Generator 0.5.0.
